# Application
spring.application.name=portfolioCMS
server.port=8000
app.version=1.0

spring.security.user.name=admin
spring.security.user.password=admin123
# ===============================
# Database Configuration (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/portfolioCMS
spring.datasource.username=root
spring.datasource.password=Test@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# File Upload Configuration
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# File Storage Location
file.upload-dir=uploads/

# ===============================
# Logging
# ===============================
logging.level.org.hibernate=ERROR
# ===============================
# Swagger / OpenAPI Configuration
# ===============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
server.servlet.context-path=/api

cors.allowed.origins=*
jwt.secretkey=hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh